# Generated by Django 3.0.6 on 2020-05-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('BudgetAmount', models.FloatField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expenses', models.ManyToManyField(blank=True, to='core.Expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('venue_name', models.CharField(max_length=255)),
                ('schedule_reception', models.TextField(blank=True)),
                ('schedule_meal', models.TextField(blank=True)),
                ('directions_car', models.TextField(blank=True)),
                ('directions_taxi', models.TextField(blank=True)),
                ('the_date', models.DateTimeField(verbose_name='wedding_date')),
                ('the_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('is_coming', models.BooleanField(default=False)),
                ('angbao', models.FloatField(blank=True)),
                ('the_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Host')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='the_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Host'),
        ),
    ]
